name: '🚀 CD — Publish'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Release Please
    steps:
      - name: 🤝 Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: yaml.min
          changelog-path: 'CHANGELOG.md'

      - name: ➕ Actions - Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          check-latest: true
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: ➕ Cache dependencies
        uses: actions/cache@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: 📦 Installing Dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: npm ci

      - name: 🚀 Building yaml.min
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run build

      - name: 📥 Publishing Package
        if: ${{ steps.release.outputs.releases_created }}
        run: npm publish --provenance
